### ISSUE TITLE
Issue of "BoxProximityField"

### ISSUE THREAD

**Issue by scyls** [oculus-samples/Unity-Movement#11]
Hi, 

When I run the package in unity I got some error which all said **'Oculus.Interaction.Deprecated.Box Proximity Field' is missing the class attribute 'ExtensionOfNativeClass'!**, I think that's because you use "BoxProximityField" class in "UITextButton" prefab and "UIToggleButton" prefab. 

However when I checked the "Oculus" package, it mentioned the "BoxProximityField" class was replaced by "ClippedPlaneSurface" class, I try to delete the "BoxProximityField" and add "ClippedPlaneSurface", the program can run without error but can not be shown into the quest pro, I'm not sure if this is because I modified the script component.

**Comment by andkim-meta** [comment]
Thank you for reporting this, we'll investigate this issue.

**Comment by andkim-meta** [comment]
Hi, please check out the dev branch of the project (https://github.com/oculus-samples/Unity-Movement.git#dev) to see if the buttons now work for you.

**Comment by andkim-meta** [comment]
Resolved in commit 8c9d1bd40b32111c60bb5299b0218d802c6b22ff to the main branch of the repository.
