### ISSUE TITLE
No input response

### ISSUE THREAD

**Issue by AyushKoul00** [oculus-samples/Unity-Movement#13]
I ran and built this app following the instructions in the readme and the configuration page. The first issue i faced was, i could not open any of the scenes inside Samples because it said they were part of a read only package.

I solved this by copying all the scenes from the samples folder into a new folder Scenes/ inside my Assets. I then added all these scenes in the build settings and built the app for Android (which was successful)

However, when i run the apk inside a quest Pro, i am able to open and run the app but it is not detecting any input (i am not able to change the menu). It is detecting the controllers and my hands but when I press any buttons or do perform any input, there is no effect.

**Comment by andkim-meta** [comment]
Hello,

Could you try to test again after updating to the latest version of the package? v1.4.0 has fixes for the ISDK prefabs, which the menus use.

Can you please also verify the following:
  1. In OVRCameraRig, can you look at OVRManager's General section and make sure Body, Face and Eye Tracking support are all enabled?
  2. In the Oculus XR Plugin settings, can you check that Quest Pro is selected as part of the Target Devices?
  3. When the app launches, did you grant permissions when prompted? This should happen when OVRManager's "Permission Requests On Startup" are checked for Body, Face and Eye Tracking.

**Comment by sohailshafiiWk** [comment]
Hello. Closing for now. Please re-open if this still occurs.
