### ISSUE TITLE
How to get VR user's skeleton information ？

### ISSUE THREAD

**Issue by artificialhumanbeing** [oculus-samples/Unity-Movement#14]
If Body Tracking Support is enabled, the OVRBody script will poll for updated body data and can be used to drive an animated skeleton or to provide information on positioning for game play. But each user 's skeletal information like body height is different. How does the OVRBody script get user's skeletal information?

**Comment by sohailshafiiWk** [comment]
Hello. We are not sure to understand what you are asking.  Are you experiencing a problem?  If so, could you describe the issue so that we can address it.

**Comment by sohailshafiiWk** [comment]
Closing for now. Please re-open if you wish to follow up.
