### ISSUE TITLE
Missing Prefabs Error

### ISSUE THREAD

**Issue by Ashray-Pai** [oculus-samples/Unity-Movement#15]
With the latest release, I am getting the missing prefab error.
![image](https://github.com/oculus-samples/Unity-Movement/assets/94760299/902613e8-eaf4-4dd5-961d-485734c24e20)

**Comment by andkim-meta** [comment]
Hello,

It looks like some prefabs that were removed inside of the github package are showing up as missing prefabs in the console. Can you remove the package and close any sample scenes, then try to add the package again to see if you still have the same issue?

**Comment by Ashray-Pai** [comment]
Hi,

I am still facing the same issue.
I created a fresh project and imported it, I got those errors.
I removed and reimported the package and the errors were still there.
Here is the link to the video: https://youtu.be/Y6Lu9MmykIM

**Comment by sohailshafiiWk** [comment]
We believe that we have resolved the issue. Can you please try the latest downloadable zip (https://github.com/oculus-samples/Unity-Movement/archive/refs/heads/main.zip) and see if it works for you without any import errors?

**Comment by Ashray-Pai** [comment]
Yes, it worked without any errors, thank you!
