### ISSUE TITLE
Open sample scenes in editor?

### ISSUE THREAD

**Issue by alysonjing** [oculus-samples/Unity-Movement#23]
Hello, 

I would like to view the sample scenes inside the Unity editor, when I try to open one it says it's in a read-only package?

![image](https://github.com/oculus-samples/Unity-Movement/assets/15023431/97432433-335f-46cd-bb64-8e077a343898)

for example I am trying to access the "smileeffect.cs" but the references seem missing. Not sure if its because of the samples was not properly connected to the read-only package? 

![image](https://github.com/oculus-samples/Unity-Movement/assets/15023431/4ca96fd0-8f5d-4131-9d26-98b44f1e4f8a)

Thanks

**Comment by Ashray-Pai** [comment]
In the ReadMe, it's mentioned that you need to copy the folder from Projects folder into your Assets folder: 
![image](https://github.com/oculus-samples/Unity-Movement/assets/94760299/ca87c039-3abd-4cd5-8166-ee0931d36f52)

**Comment by alysonjing** [comment]
Thanks, I was hoping to overwrite some scripts (in a different folder than scenes), but I think the scripts are probably read-only. Thank you. closed.
