### ISSUE TITLE
Unable to start sample-scenes

### ISSUE THREAD

**Issue by Mrihs** [oculus-samples/Unity-Movement#26]
Hello! After adding the sample-scenes from the package to the project we'll get this error:

Library\PackageCache\com.meta.movement@218e21a04d\Runtime\Scripts\AnimationRigging\RetargetingLayer.cs(329,31): error CS1061: 'Transform' does not contain a definition for 'SetLocalPositionAndRotation' and no accessible extension method 'SetLocalPositionAndRotation' accepting a first argument of type 'Transform' could be found (are you missing a using directive or an assembly reference?)

Do you know what to do with this error?

**Comment by andkim-meta** [comment]
Hello, can you check your unity version and ensure that it is 2021.3.21f1 or newer? Also, can you make sure to update the animation rigging package to the latest supported by that unity version?

**Comment by HalleFord** [comment]
Hi. I have the same issue, and am using Unity 2021.3.3f1. When I look in Package Manager, it says I have Animation Rigging Version 1.2.1 - January 12, 2023.

**Comment by Ashray-Pai** [comment]
@HalleFord as we the requirements you'll need Unity 2021.3.21f1 (2021 LTS) or newer installed so 2021.3.3 will not work.

**Comment by HalleFord** [comment]
I apologize I misread the version number. This issue no longer occurs for me when now using Unity 2021.3.27f1.

**Comment by sohailshafiiWk** [comment]
Closing for now. Please re-open if you wish to follow up
