### ISSUE TITLE
InputSubsystem Not Found

### ISSUE THREAD

**Issue by HalleFord** [oculus-samples/Unity-Movement#27]
I receive a "InputSubsystem Not Found" error when trying to play any of the scenes under Meta Movement => Samples => Scenes.

Steps to reproduce:
1. Created new Unity 2021.3.27f1 project
2. Imported Oculus Integration SDK version 54.1
3. Configured all settings indicated in: https://developer.oculus.com/documentation/unity/unity-conf-settings/
4. Imported Movement SDK
5. Tried to play cube scene. It works great.
6. Tried to play movement samples scenes. Scenes render to headset, but character does not move with my controller, head, or face movements.

I am using an Oculus Quest 2 connected to a Windows machine using Link

Note: During step #2, I selected "Yes" when prompted: "This project is using the new input system package but the native platform backends for the new input system are not enabled in the player settings. This means that no input from native devices will come through. do you want to enable the backends?"

Thank you for your assistance!

**Comment by sohailshafiiWk** [comment]
Hello. We are sorry that you are running into issues.

It is unclear from your description if this problem occurs if you try the app stand-alone (on the Quest HMD) or only when you run over Link.  Can you help us isolate the problem more by following the  troubleshooting guide here? https://developer.oculus.com/documentation/unity/move-troubleshooting/

Please let us know how far you make it and please note any log messages regarding tracking technologies failing to start.

**Comment by HalleFord** [comment]
Thank you for this. Per the above guide, I enabled Developer Runtime Features, Passthrough over Oculus Link, Eye tracking over Oculus Link, and Natural Facial Expressions over Oculus Link. Body tracking and hand tracking now works, but eye tracking and facial expressions do not work.

**Comment by sohailshafiiWk** [comment]
Hello again. Quest 2 doesn’t support the sensors for camera-driven face tracking. This is only supported on Quest Pro. I'm going to close this issue for now. Please report any other issues, if any are encountered.
