### ISSUE TITLE
Can you please give the solution of this compile error

### ISSUE THREAD

**Issue by hyeonmin11** [oculus-samples/Unity-Movement#30]
![image](https://github.com/oculus-samples/Unity-Movement/assets/79415795/0d7d3abb-7f6b-439c-b469-073ec0057da6)

Thanks.

**Comment by sohailshafiiWk** [comment]
Hello. Have you tried to download a recent version of the Oculus Integration SDK? Can you navigate to https://developer.oculus.com/downloads/package/unity-integration, download 53.1 or newer, and then try to integrate it into your project? Before you do, please remember to delete your project's Assets/Oculus folder beforehand, while the project is closed.

**Comment by sohailshafiiWk** [comment]
Closing for now. Please let us know if you need additional assistance.
