### ISSUE TITLE
pose detection & tracking

### ISSUE THREAD

**Issue by hyeonmin11** [oculus-samples/Unity-Movement#32]
First of all, I'm very interested in this. So I am reviewing the code, but it is not quiet easy. I want to know the primary script where each pose detection and tracking is happening because I am trying to learn the logic of pose detection and tracking
Can you please explain what scripts  are operating for those?
\Thanks!

**Comment by sohailshafiiWk** [comment]
We are closing this request as this mechanism should be used for raising issues, not asking general questions.  We suggest that you join many of the public discussion threads for this type of general knowledge.  Good luck in your learning!
