### ISSUE TITLE
Cannot open project

### ISSUE THREAD

**Issue by owlandfox** [oculus-samples/Unity-Movement#35]
Download source via Git and upon trying to add the porject to Unity hub it says the project is not valid?

Tried in 2021.3.30 and 2022.3.7

Tried to also directly open a scene from within the folder and same issue? Do I need to change some thing?

**Comment by sohailshafiiWk** [comment]
Hello. Please note that this sample is distributed as a package, as opposed to a project. Please see the "Getting Started" section of our readme. Please also see the "Samples" section regarding our scenes. Furthermore, we recommend using 2021 LTS for now.

**Comment by sohailshafiiWk** [comment]
Closing for now. Please let us know if you need any additional help with using our package.
