### ISSUE TITLE
Issues with retargeting

### ISSUE THREAD

**Issue by owlandfox** [oculus-samples/Unity-Movement#36]
I have setup my avatar according to documentation and all looks correct in the mapping - 
![image](https://github.com/oculus-samples/Unity-Movement/assets/15714783/98d20e35-4453-42eb-9e33-6375e73bc9b3)

Correct scripts have been added to character -
![image](https://github.com/oculus-samples/Unity-Movement/assets/15714783/1f91803d-b587-486e-a6cc-ec39dc26ab5a)

But the animation is completely out. Head is too high and not moving in sync with upper chest and shoulders, and hands are not rotating at the correct place. Wrist rotation seems to be happening higher up the lower arm.
![image](https://github.com/oculus-samples/Unity-Movement/assets/15714783/bdc4e83e-13b8-4907-991b-63a89b756e9d)

**Comment by owlandfox** [comment]
> I have setup my avatar according to documentation and all looks correct in the mapping - ![image](https://user-images.githubusercontent.com/15714783/268040506-98d20e35-4453-42eb-9e33-6375e73bc9b3.png)
> 
> Correct scripts have been added to character - ![image](https://user-images.githubusercontent.com/15714783/268040681-1f91803d-b587-486e-a6cc-ec39dc26ab5a.png)
> 
> But the animation is completely out. Head is too high and not moving in sync with upper chest, and hands and not rotating at the correct place. Wrist rotation seems to be happening higher up the lower arm. ![image](https://user-images.githubusercontent.com/15714783/268042321-bdc4e83e-13b8-4907-991b-63a89b756e9d.png)

**Comment by sohailshafiiWk** [comment]
Hello. It appears that your character might need IK constraints, specifically deformation constraint that attempts to preserve the character's constraints using Animation Rigging. After importing the package files (see my reply in https://github.com/oculus-samples/Unity-Movement/issues/35), please look at the prefab ArmatureSkinningUpdateRetargetUser used in MovementRetargeting.unity.  You can add similar constraints by right-clicking on a character, then navigating to Movement Samples -> Body Tracking -> Animation Rigging Retargeting (constraints).

**Comment by owlandfox** [comment]
![com conduit xr2022-20230922-144447](https://github.com/oculus-samples/Unity-Movement/assets/15714783/0f575787-a0c8-47ec-ba08-52e5ff101d59)
So even when building the retargeting scene to device (obviously without making any changes to it as I cant) the rig is completely out. Added a secondary robot via the UI with animation retargeting and you can see the mesh is completely deached from rig. Any idea what could be happening here?

**Comment by owlandfox** [comment]
I downgraded the project back to 2021.3.30 and it did correct the sample scene and retargeted character. I re-applied all the constraints to my character to match the retargeted sample robot and its much better but still quite off as you can see my hands are super long and still twisting at a strange place on the wrist. Neck is at a strange height above the shoulders too. Any advice to further refine this much appreciated -
![com conduit xr2022-20230926-003536](https://github.com/oculus-samples/Unity-Movement/assets/15714783/6e8add0d-d8ed-410a-b415-20e367ba7f4f)


> Can you indicate which version of Unity you are using? There is currently a retargeting bug with 2022 and 2023 that is being investigated. See #29

**Comment by sohailshafiiWk** [comment]
We are currently looking into a modified deformation system that might be able to help. For now, you can possibly use `_jointRotationTweaks` on `RetargetingLayer` to manually adjust bones on the humanoid.

**Comment by owlandfox** [comment]
In terms of getting the mesh and rig to perform/deform as well as the high fidelity character would we need to match the exact pose/bone length/rotations as the source character we are retargeting from. If so, which model are we actually retargeting from when applying the constraints from the samples scripts?

**Comment by sohailshafiiWk** [comment]
`OVRUnityHumanoidSkeletonRetargeter` and the class that inherits from it, `RetargetingLayer`, effectively retarget from `OVRSkeleton`'s `Bones` to the humanoid bones. Note that `OVRUnityHumanoidSkeletonRetargeter` inherits from `OVRSkeleton`. The `OVRSkeleton` also gives the body tracking rest pose in the `BindPoses` variable.

**Comment by andkim-meta** [comment]
Hello. We have some updated documentation on setting up a retargeted character here that should help resolve the issue: [Setting up a character for body tracking](https://developer.oculus.com/documentation/unity/move-body-tracking/#setting-up-a-character-for-body-tracking). Closing this issue for now.

**Comment by karunateam** [comment]
It doesn't seem that the suggested answer of following the new documentation is sufficient to close out this ticket. @owlandfox Can you confirm that following the new documentation fixed your issue?
