### ISSUE TITLE
Replace default avatar with other

### ISSUE THREAD

**Issue by Softelectro** [oculus-samples/Unity-Movement#38]
Hello,
I want to replace the default avatars with others (like avatars from Character Creator 4). Despite several attempts, I can't reproduce the test scene (MovementHipPinning).

- Automatic mapping (setup character for body tracking / format: unity Humanoid) gives me correct hand tracking, but the avatar is completely deformed (mainly on the arms).
- And the oculus skeleton format completely distorts my character when I setup the corresponding bones.

What avatar source do you use (CC4D, Mixamo, ...)?
Are there any specific parameters to take into account during generation?

Thank you.

**Comment by owlandfox** [comment]
Wouls also like more detail on this. struggling on same setup

**Comment by andkim-meta** [comment]
Hello. For targeting characters that are Unity Humanoid, we recommend looking at the MovementRetargeting scene. In that sample scene, we apply tracking to a Unity Humanoid character, then display how to use animation rigging to fix up issues such as the deformation. The components we would recommend looking at are:

- Deformation Constraint (animation job that fixes mesh deformation from tracking)
- Two Bone IK Constraint (animation job that adjusts the arm for the tracked hand position after deformation constraint runs)
- (Optional) RetargetingLayer.JointRotationTweaks (field to apply joint rotation tweaks for the retargeted character)
- (Optional) Blend Hand Constraints (handling edge cases with Two Bone IK for the hand)

We also have a one-click helper menu that can setup these constraints on your character, available under "GameObject -> Movement Samples -> Body Tracking -> Animation Rigging Retargeting (constraints)".

**Comment by andkim-meta** [comment]
Hello. We have some updated documentation on setting up a retargeted character here that should help resolve the issue: [Setting up a character for body tracking](https://developer.oculus.com/documentation/unity/move-body-tracking/#setting-up-a-character-for-body-tracking). Closing this issue for now.
