### ISSUE TITLE
Meta Avatar Integration

### ISSUE THREAD

**Issue by WoodsFiend** [oculus-samples/Unity-Movement#39]
Wondering if their are any plans to implement the Movement SDK with Meta Avatars or if someone has been able to get them working together?

I tried a few different things and they don't seem compatible. Would definitely increase the use of Meta avatars if they worked with the Movement SDK.

**Comment by sohailshafiiWk** [comment]
The Movement SDK and the Avatar SDK are intended for different use cases.  The Movement SDK is typically used if you want to embody something other than the Meta Avatars or if you want raw body tracking information while the Avatar SDK gives you a more complete packaged experience with the Meta Avatars.  Can you clarify what you are trying to accomplish so that we can better respond?

**Comment by WoodsFiend** [comment]
I think I may have misunderstood the Movement SDK. I thought it was capable of full body tracking with leg movement as shown at Connect event but it seems that is not yet available in the SDK. I just wanted to give the Meta avatar walking and crouching. 

Maybe there is a better solution? I just figured out how to use Unity skinning on Meta avatars so I get a rig in the hierarchy, now trying to apply an animator to it.

**Comment by sohailshafiiWk** [comment]
Correct.  The body tracking improvements announced at Connect are available in December.  They are available in Movement SDK first.  We would suggest you reach out to the Avatar SDK team for details on when they will be available in the Avatar SDK.

**Comment by sohailshafiiWk** [comment]
Correct.  The body tracking improvements announced at Connect are available in December.  They are available in Movement SDK first.  We would suggest you reach out to the Avatar SDK team for details on when they will be available in the Avatar SDK.

**Comment by sohailshafiiWk** [comment]
Closing for now. Please open a new issue if you run into more problems.
