### ISSUE TITLE
Multiple Prefab Import Errors in Unity Package 'com.meta.movement'

### ISSUE THREAD

**Issue by BlackFox16** [oculus-samples/Unity-Movement#40]
### Description

I'm encountering multiple errors when attempting to import prefabs from the 'com.meta.movement' Unity package. These errors suggest that the files might be corrupt or are missing Variant parent or nested Prefabs.

### Steps to Reproduce

1. Import the `com.meta.movement` package version 3.1.1 (2023-09-21) into Unity.
2. Observe the errors in the console as Unity tries to import prefabs related to UI components and legacy menus.

### Expected Behavior

Prefabs should import seamlessly, enabling the utilization of the sample UI and legacy menus provided by the package.

### Actual Behavior

The import process results in multiple errors, preventing the use of the prefabs. The following errors are displayed:

- `[20:57:39] Problem detected while importing the Prefab file: 'Packages/com.meta.movement/Samples/Prefabs/UI/Legacy/RetargetingMenuLegacy.prefab'. The file might be corrupt or have a missing Variant parent or nested Prefabs.`
- `[20:57:40] Problem detected while importing the Prefab file: 'Packages/com.meta.movement/Samples/Prefabs/UI/SceneSelectMenu.prefab'.`
- `[20:57:41] Problem detected while importing the Prefab file: 'Packages/com.meta.movement/Samples/Prefabs/UI/TogglesMenu.prefab'.`
- `[20:57:42] Problem detected while importing the Prefab file: 'Packages/com.meta.movement/Samples/Prefabs/UI/HipPinningMenu.prefab'.`
- `[20:57:43] Problem detected while importing the Prefab file: 'Packages/com.meta.movement/Samples/Prefabs/UI/Legacy/SceneSelectMenuLegacy.prefab'.`
- `[20:57:43] Problem detected while importing the Prefab file: 'Packages/com.meta.movement/Samples/Prefabs/UI/Legacy/HipPinningMenuLegacy.prefab'.`

### Screenshots

<img width="717" alt="image" src="https://github.com/oculus-samples/Unity-Movement/assets/118074019/8d36d1e4-e875-48f1-b561-b22106706a04">

### Environment

- Unity Version: 2022.3.11
- Operating System: Windows

### Additional Context

The errors occurred using the recent release of the package, version 3.1.1, dated 2023-09-21.

**Comment by sohailshafiiWk** [comment]
Hello. Can you please try importing the integration package from [https://developer.oculus.com/downloads/package/unity-integration/](https://developer.oculus.com/downloads/package/unity-integration/) into the project? The Oculus/VR and Oculus/Interaction folders from the package are required to work with Movement.

**Comment by BlackFox16** [comment]
it works! Thanks
