### ISSUE TITLE
Full body tracking

### ISSUE THREAD

**Issue by BlackFox16** [oculus-samples/Unity-Movement#41]
Hello,

is the recently announced update for full body tracking (including legs) already available in the recent com.meta.movement package version 3.1.1 ? 

Thank you.

**Comment by sohailshafiiWk** [comment]
The release containing Generative Legs is planned for December.  As described at Connect, this release generated plausible legs.  It does not provide full tracking for legs.

**Comment by BlackFox16** [comment]
Thanks!
