### ISSUE TITLE
Various Type Name does not exist in OVR*

### ISSUE THREAD

**Issue by Birillox** [oculus-samples/Unity-Movement#45]
Hi, I downloaded (https://assetstore.unity.com/packages/tools/integration/meta-xr-all-in-one-sdk-269657) following the entire procedure and managed to install it correctly and test it.
The problem arises when I try to use (https://github.com/oculus-samples/Unity-Movement) because, at the end of the download and installation on the Unity package manager, I get several error messages:
"Library\PackageCache\com.meta.movement@269e4a24cb\Runtime\Scripts\AnimationRigging\Legacy\FullBodyCustomMappings.cs(112,43): error CS0117: 'OVRPlugin.BoneId' does not contain a definition for 'FullBody_End'"
[..]
"Library\PackageCache\com.meta.movement@269e4a24cb\Runtime\Scripts\AnimationRigging\Legacy\FullBodyCustomMappings.cs(87,61): error CS0117: 'OVRPlugin.BoneId' does not contain a definition for 'FullBody_RightHandRingDistal' "

Version sdk: 59.0.0
Version Movement: 4.0.0
What did I do wrong?

**Comment by sohailshafiiWk** [comment]
Hello. Full body joints require v60, and going forward please make sure that your OS version is v60 or higher and that the UPM packages (com.meta.xr.sdk.core and related) are v60 or higher. Please also refer to this project's README for more information. Closing this issue for now.
