### ISSUE TITLE
[OVREyeGaze] Failed to start eye tracking.

### ISSUE THREAD

**Issue by MentalFairy** [oculus-samples/Unity-Movement#47]
Hello fellow developers :) 

Been trying to get this working over oculus air link, but with no success yet.

Both Oculus Software/firmware have been freshly installed / updated.
Using the latest Oculus SDK.

Verified all older posts and solutions regarding this warning, but nothing helped.

![image](https://github.com/oculus-samples/Unity-Movement/assets/14876468/f6cbdf13-abc0-4b25-922c-a984c3f16974)

![image](https://github.com/oculus-samples/Unity-Movement/assets/14876468/6d8fa5d9-b204-41f4-b01b-92cf34edce25)

![image](https://github.com/oculus-samples/Unity-Movement/assets/14876468/dfb74115-e2d0-4317-a177-0425988d349d)

![image](https://github.com/oculus-samples/Unity-Movement/assets/14876468/3fc9eef4-6043-4a59-b5a7-7217f1a57a09)

![image](https://github.com/oculus-samples/Unity-Movement/assets/14876468/aec01121-d246-4fed-934b-3cc617b9aeca)

![image](https://github.com/oculus-samples/Unity-Movement/assets/14876468/d6bd87d0-a4a5-41f8-a895-db2f49eb6f80)

[Oculus_Logs_DESKTOP-0BSF5QS_20231225_122821.zip](https://github.com/oculus-samples/Unity-Movement/files/13765710/Oculus_Logs_DESKTOP-0BSF5QS_20231225_122821.zip)

Hope all the above information helps, and thank you so much for taking the time!

**Comment by andkim-meta** [comment]
Hello. The logs that were provided show that you were using a Quest 2 headset for eye tracking. Currently, Eye Tracking is only available on the Quest Pro headset and is unavailable on the Quest 2 headset. Can you test again with a Quest Pro headset and upload additional logs if you still encounter this issue?

**Comment by sohailshafiiWk** [comment]
Closing for now. Please let us know if you run into more problems.
