### ISSUE TITLE
OVREyeGaze doesn't track per eye (cross eyed not possible)

### ISSUE THREAD

**Issue by Pvanderlaan89** [oculus-samples/Unity-Movement#49]
When checking the MovementAura and MovementHighFidelity scenes, I noticed the mirrored avatars don't look cross eyed when I cross my eyes. I conclude from this that the OVREyeGaze script doesn't track per eye but instead gives back some averaged value. This contradicts to what is stated in the documentation:

https://developer.oculus.com/documentation/unity/move-overview/#eye-tracking 
> The abstracted eye gaze representation that the API provides (**gaze state per eye**) allows a user’s character representation to make eye contact with other users. This can significantly improve your users’ social presence.

Tested with Unity 2022.3.11f1, Meta All-in-One 60.0.0 and Meta Movement 4.0.1

**Comment by sohailshafiiWk** [comment]
Hello. We currently output a fixed convergence distance which prevents users from crossing their eyes. This may change in the future, but is currently a limitation of the implementation. Please let us know if you have any other questions.

**Comment by Pvanderlaan89** [comment]
Ok, thank you for your answer. I guess this is a good default behavior for most situations.

In my case (scientific VR experiments), it is probably beneficial to have the option to fully individually track each eye. Also, when trying the MovementHighFidelity demo, when I look very closely at my mirrored avatar, I can't see which eye I'm looking at, something which is possible in the real world.

**Comment by sohailshafiiWk** [comment]
Thank you for the feedback, we will note this in our product backlog of requests. For now we will close this issue. If you encounter different issues with eye tracking, please feel free to open a new issue.
