### ISSUE TITLE
custom avatar retargeting error with iobt(full body tracking)

### ISSUE THREAD

**Issue by keyone957** [oculus-samples/Unity-Movement#52]
https://github.com/oculus-samples/Unity-Movement/assets/55803332/dff85083-e42e-47df-b6e2-1158b2f1b4a0

=>Unity PlayMode

<img width="194" alt="image" src="https://github.com/oculus-samples/Unity-Movement/assets/55803332/6025af21-3ba7-40b3-89e3-0508e4dc5000">
==>original avatar fbx 

I want to do full body tracking using iobt. If you install the meta movement SDK and view the sample scene, the avatar will appear properly. However, if I take the avatar fbx file I use and use it, the avatar comes out distorted like that. Is there a way to automatically and accurately perform avatar retargeting?

i use Meta Quest Pro
unity 2023.3.17f1
please help me!!!!

**Comment by LoganLane** [comment]
This looks really similar to the issue that I was experiencing in issue #51. Disabling "Apply Root Motion" on the animator component seems to have resolved my issue. I would try that and see if doing that resolves the issue.

**Comment by keyone957** [comment]
> This looks really similar to the issue that I was experiencing in issue #51. Disabling "Apply Root Motion" on the animator component seems to have resolved my issue. I would try that and see if doing that changes anything.

Hmm... I tried that method too, but the same problem occurs. When retargeting a custom avatar, do you need to fine-tune the component values?

**Comment by sohailshafiiWk** [comment]
Hello. Is the Translation DoF setting enabled on the character's avatar, as referenced in https://developer.oculus.com/documentation/unity/move-body-tracking/#setting-up-a-character-for-body-tracking? The latest version of the Movement samples on GitHub should report an error if that is not enabled.

**Comment by keyone957** [comment]
> Hello. Is the Translation DoF setting enabled on the character's avatar, as referenced in https://developer.oculus.com/documentation/unity/move-body-tracking/#setting-up-a-character-for-body-tracking? The latest version of the Movement samples on GitHub should report an error if that is not enabled.

Thanks for answering my problem! I'll give you an answer after I give it a try!

**Comment by sohailshafiiWk** [comment]
Hello, I wanted to see if our suggestion helped you not?

**Comment by sohailshafiiWk** [comment]
Since there hasn't been an update in a while we are closing this issue. Please let us know if you need more help.
