### ISSUE TITLE
Face expression and eye gaze data

### ISSUE THREAD

**Issue by hyungwoo822** [oculus-samples/Unity-Movement#53]
Hello Oculus Developers, I'm wonder that we can get the raw data of facial blendshape and eye gaze data. 
I'm preparing some blendshape works so if there is anybody who knows the way to get these data please let me know.

**Comment by sohailshafiiWk** [comment]
Hello. You can get eye gaze data from functions such as ovrp_GetEyeGazesState as seen in OVREyeGaze, and GetFaceState2 as seen in OVRFaceExpressions in the current version of the SDK. It is currently not possible to access raw data. We will close this issue for now. Please post questions such as this on our forums [here](https://communityforums.atmeta.com/t5/Developer/ct-p/developer).
