### ISSUE TITLE
Hand tracking not working in unity editor using link

### ISSUE THREAD

**Issue by Extrys** [oculus-samples/Unity-Movement#54]
Im using currently, Windows 11, Quest pro, quest 2 and 3
i have tried in a new project in unity 2022.3.7f1
with the newest Meta all in one SDK, version 60
the project is on a private git repo, so me and a friend have both access to it
My settings on the oculus pc app is identical to his settings, my headsets are also in developer mode
but for my friend their hands work, and mine dont, the only difference is that he is using windows 10 and im using windows 11

these are the logs when hitting play. i have set the ovr rig building block and the had tracking building block and made sure hands fields are set as left and right respectivelly, in Quest features i have set hands only
![image](https://github.com/oculus-samples/Unity-Movement/assets/38926085/f2c62eee-0184-42f2-9fb7-1769d0c7c3fa)

**Comment by sohailshafiiWk** [comment]
Can you confirm if you see hand-tracking if the project is run as an *.apk as opposed to running over Link.  Also, have you taken a look at our [https://developer.oculus.com/documentation/unity/unity-link/?](https://developer.oculus.com/documentation/unity/unity-link/)

**Comment by Extrys** [comment]
It works when runned as apk, but not in editor, the problem is that our builds takes a lot to do and i can not develop properly hand tracking apps because of this

**Comment by Extrys** [comment]
is there any new, even if its just informative about, im running out of hope on being able to make hand tracked apps

**Comment by sohailshafiiWk** [comment]
Hello. We've been investigating the issue internally. We have a few questions:
1) Ensure that under ProjectSettings -> XR Plugin Management -> "Oculus" is selected.
2) From the menu, selecting Oculus -> Tools -> Project Setup Tool and then selecting "Apply All" from the recommended settings.
3) When running the project, try toggling hand tracking off and then on in the HMD. 
4) Could you test with disabling automatic switching to hand tracking under the  movement tracking settings and then manually triggering the switch to hand tracking button in quick settings?

**Comment by Extrys** [comment]
> Hello. We've been investigating the issue internally. We have a few questions:
> 
> 1. Ensure that under ProjectSettings -> XR Plugin Management -> "Oculus" is selected.
> 2. From the menu, selecting Oculus -> Tools -> Project Setup Tool and then selecting "Apply All" from the recommended settings.
> 3. When running the project, try toggling hand tracking off and then on in the HMD.
> 4. Could you test with disabling automatic switching to hand tracking under the  movement tracking settings and then manually triggering the switch to hand tracking button in quick settings?

sorry the delay i didnt got notification on this.

i have tried this you have tell me now, and its still not working

**Comment by Extrys** [comment]
do you need more info im willing to help in any way, just tell me what you need, if you need logs or whatever thing

**Comment by sohailshafiiWk** [comment]
Can you use Meta Quest Developer Hub to report a Development Runtime Issues bug? And put the GitHub issue link in the description? Please select the option to include Unity logs.

**Comment by Extrys** [comment]
Ok, thanks to [Dance_M](https://forum.unity.com/members/dance_m.672411/) (unity forum user), I got it fixed
he told me about some ultra leap incompatibility, so as long as i had installed the ultra leap software even if it is not running, it conflicts with the Meta hand tracking, so i just uninstalled ultra leap entirely and it just work perfectly right now

It would be nice to have this in mind in case more people are suffering from this problem, because this is not easy to find

**Comment by Extrys** [comment]
I will close this issue now, thanks for your time
