### ISSUE TITLE
Body Tracking PCVR

### ISSUE THREAD

**Issue by HalfwitSundays** [oculus-samples/Unity-Movement#55]
Hey, I'm trying to use the Movement SDK to get upper body tracking for a pinned hip from the first person. Some of it still needs work but I'd just like to know if the SDK is able to work on a PC build? I got it to work in editor using the Windows Build target but when I build it to an exe. nothing shows up except for the skybox, any ideas

https://github.com/oculus-samples/Unity-Movement/assets/103476773/70e162f0-cfdb-4a03-b69a-be5d985187f4

https://github.com/oculus-samples/Unity-Movement/assets/103476773/144ab8db-0a91-4047-adb8-880e7b2400b8

**Comment by sohailshafiiWk** [comment]
Hello. We have tried unsuccessfully to duplicate your problem and are a bit at a loss. It looks like you were able to see this problem with a pretty simple scene.  If it doesn't contain any proprietary information or purchased assets, would you be willing to post a version that we could use to duplicate the issue? If not, can you indicate your OS version and Unity version and use the Developer Hub to report a ticket (include a link to the GitHub problem) and please select the option that will include the Unity logs.

**Comment by sohailshafiiWk** [comment]
Also, when building can you make sure the Platform selected in "Windows, Mac, Linux" as opposed to "Universal Windows Platform?"

**Comment by HalfwitSundays** [comment]
Hey sorry it took a bit to get back to you but I've attached the project. You can find the scene I'm using (with a different background) at Assets -> Demo Scene. It's built off the Unity URP Sample Environments but doesn't incorporate anything but the skybox, still just a stripped scene. Also, completely unrelated but have you guys tried to get passthrough running on a PCVR app? Just put a "---" in your message if it's a unknown on your end. Cheers

Google Drive Link: https://drive.google.com/file/d/1WEG-zlhOJQgDI_dd5b3Zq_Nf0a3UPVV8/view?usp=sharing

**Comment by sohailshafiiWk** [comment]
Passthrough should work via PCVR. As for your project please try the following:
1. Open project settings.
2. Navigate to Graphics.
3. In right side menu select Scriptable Render Pipeline Settings.
4. Select little bulls eye icon on right and select either PC_High or PC_Low asset.
5. Build for Windows, Linux, Mac to create a playable .exe file

**Comment by sohailshafiiWk** [comment]
We have not seen a response for a while. Closing for now. Please let us know if you need additional assistance.
