### ISSUE TITLE
IOBT turns off when passthrough tuns on

### ISSUE THREAD

**Issue by UniWorkerPtyLtd** [oculus-samples/Unity-Movement#57]
I modified the MovementRetargeting sample to turn on passthrough after 10 seconds.

Before passthrough turns on, I can use `adb shell dumpsys activity service com.oculus.bodyapiservice.BodyAPIService` and see that `"iobt" : true`. But after it turns on, `adb shell` immediately returns `"iobt" : false`

Is this expected behaviour? Does IOBT not work when passthrough is turned on?

**Comment by sohailshafiiWk** [comment]
IOBT is a suggested fidelity mode and not a requirement of the API. This system is implemented to manage the performance so the CPU is not over-taxed.  The sample has Generative Legs, and IOBT enabled.  If Passthrough is also enabled, the system will degrade the body fidelity setting from high (IOBT) to low (3 pt tracking) for most use cases (only exception is 30 Hz hands).  So, for now, you need to make the trade-off between going into hands-30Hz in that scene or selecting either full body (Generative Legs) or IOBT.  We are optimizing performance in the system, so this may change in the future.  Note that the way that it is implemented now, if you exit passthrough, then IOBT will be re-enabled and it is largely transparent to the app.

**Comment by UniWorkerPtyLtd** [comment]
Thank you so much for your detailed response! It's such a thrill to hear accurate information from the developers.

So, to confirm: passthrough + IOBT + 30Hz hands (is this 'low' setting in Unity?) should work?

**Comment by sohailshafiiWk** [comment]
Yes; in general. However, as stated above IOBT is a requested fidelity and not guaranteed in all conditions. There could be other changes in the future (e.g. new device, new feature) that would cause a condition where the performance management would decide that IOBT would be dropped back to low fidelity to reduce system strain.  We would suggest that you query the state of IOBT in your configuration if it is critical for your game play

**Comment by UniWorkerPtyLtd** [comment]
Thanks so much! I look forward to adding IOBT to PozeAR!

**Comment by sohailshafiiWk** [comment]
Please let us know if you face other issues. I will close this issue.
