### ISSUE TITLE
Invalid feet positions in HipPinning sample when the model is rotated. 

### ISSUE THREAD

**Issue by dledents** [oculus-samples/Unity-Movement#58]
Steps to reproduce:
1. Open MovementHipPinning sample.
2. Rotate Objects 90 degrees around Y axis. 
![image](https://github.com/oculus-samples/Unity-Movement/assets/32562250/7966630d-7261-44a0-9cdf-a576f76d200f)
3. Rotate OVRCameraRig 90 degrees around Y axis as well.
4. Enable mesh and material for C_wetsuit_PLY under HighFidelityHipPinningFirstPerson as on screenshot below. 
![image](https://github.com/oculus-samples/Unity-Movement/assets/32562250/7dccf5c5-aea7-4b43-9b0b-3926e52a8580)
5. Run the sample.
6. Feet are directed to the left.
![com itseez3d metaperson quest handtracking sample dev-20240215-120935](https://github.com/oculus-samples/Unity-Movement/assets/32562250/ffc4f2b2-b121-42d4-acc7-06c14a8753fe)

**Comment by sohailshafiiWk** [comment]
Hello. We've pushed a fix to address this bug in the #dev branch. Please try the scene in that branch to see if the problem has been resolved for you.

**Comment by dledents** [comment]
I don't see this problem in the sample from the dev branch. Thank you.
