### ISSUE TITLE
Movement Aura sample runs but everything frozen (no tracking) on Quest Pro

### ISSUE THREAD

**Issue by matteo411** [oculus-samples/Unity-Movement#6]
I'm brand new to Unity and I think I followed the instructions correctly to deploy the MovementAura sample to the Quest Pro but the mirrored alien character doesn't mirror my tracked movements at all. She is frozen. Is there a setting I need to check?

![aura_frozen](https://user-images.githubusercontent.com/505881/203255029-a25bf990-438c-4d83-a7d7-d328263d0233.jpg)

**Comment by lvialle** [comment]
And... I have exactly the same problem, I can only see the virtual remotes working, I can push the button at the left and load the other scenes. Even on the seated scene, the mirror body is still having the default pose and is not seated.

I got it working using Air Link for facial expressions and eyes tracking, but on standalone, only head tracking is working.

**Comment by lvialle** [comment]
I finally figured what was missing. In you Aurora Rig, there are scripts (unfortunately I am on another computer right now, so I can't provide the complete path), select the OVRCameraRig, you will find a panel with Quest features, where you can set Body, Face and Eye tracking support to supported/required. Then below, there is a folded section named "Permission Requests on Startup", check them, then your app will ask for the permissions on the first startup, and it should works.

**Comment by sohailshafiiWk** [comment]
Hello,

That is correct. Permissions are required for startup. In the dev branch you can see a revised readme that we are working on. 

@matteo411 Can you please verify the following:

1. In OVRCameraRig, can you look at OVRManager's General section and make sure Body, Face
and Eye Tracking support are all enabled?
2. When the app launches, did you grant permissions when prompted? This should
happen when OVRManager's "Permission Requests On Startup" are checked for
Body, Face and Eye Tracking.
3. In your Quest Pro's Movement Tracking section (system settings), 
have you enabled face and eye tracking?

**Comment by matteo411** [comment]
OK in the inspector for OVRCameraRig >> Quest Features >> General tab I changed Body Tracking Support, Face Tracking Support, Eye Tracking Support from "Disabled" to "Supported". Also under OVRCameraRig >> Quest Features >> Build Settings I set the checkboxes under "Permission Requests On Startup" for Body Tracking, Face Tracking, Eye Tracking.

Now the facial expressions and eye blinking work for the Aura character, but eyeball movement, head movement, and hand tracking movement area all still not working. There is a UI menu on the left but I can't select anything.

**Comment by lvialle** [comment]
You have to push the buttons with the controllers, just by reaching them

**Comment by matteo411** [comment]
> You have to push the buttons with the controllers, just by reaching them

I can depress the buttons with the controller, but nothing happens. The circle selection stays on Face

**Comment by sohailshafiiWk** [comment]
1. On your Quest Pro device, check the Movement Tracking settings and make sure that Eye Tracking is switched on in the Eye Tracking section of that menu.

2. In the "System" settings menu, can you click on Software Update and look at your Runtime version? Does it start with 46 or 47? There was update pushed out recently that you might need.

3. Also is this happening over Link or via builds? To have these features run over Link, make sure that the Oculus software on your machine has Developer Runtime features, Eye tracking, and Natural Face Expressions over Link marked as enabled in the "Beta" section of "Settings."

4. When you press the buttons, do you see any errors in the Console? The buttons allow scene navigation so you should add all of the Sample scene to the build settings for them to work.

**Comment by matteo411** [comment]
@sohailshafiiWk 
1. Yes, under Movement Tracking settings I've got everything enabled: Natural Facial Expressions, Eye Tracking, Hand Tracking
2. In System settings >> Software Update it says No Updates Available. System Version = 47421700960000000, Version = 46.0.0.261.0.415550680, Runtime Version = 46.0.0.261.0.415550559, OS Version = user-47421700960000000
3. This is built as an apk and deployed to the device but I do have those beta settings enabled anyways. How do I try running the app over link instead of deployed?
4. Thanks for this tip. After adding all 4 scenes in the build settings correctly change the scene now when I press them.

**Comment by sohailshafiiWk** [comment]
When the app launches, does it ask you for permissions for all tracking technologies (even the ones that fail, that is)?

In Player settings under XR Plug-in Management, have you checked the Oculus checkbox? Do you have XR Plug-in installed in your project?

To try these features over Link, you will need to go to the Oculus app on your machine, click on Settings then navigate to the "Beta" tab. Developer runtime features, eye and  face tracking should be enabled there. You might want to try the public test version (https://www.meta.com/help/quest/articles/headsets-and-accessories/oculus-rift-s/public-test-channel/) to make sure that body tracking functions over Link as well.

**Comment by matteo411** [comment]
In XR plug-in management I can't check the Oculus checkbox, it is disabled:

![image](https://user-images.githubusercontent.com/505881/205717829-d265d288-7ff7-4aa2-ac9e-1aa6451b0cb3.png)

**Comment by sohailshafiiWk** [comment]
Can you try un-checking the OpenXR checkbox and seeing if the Oculus checkbox is available after?

**Comment by matteo411** [comment]
@sohailshafiiWk yes! when I switch the player setting from OpenXR to Oculus now all the trackers work!

**Comment by sohailshafiiWk** [comment]
@matteo411 Glad it works now! Have fun!
