### ISSUE TITLE
Move samples to Samples~ folder for Unity Package Manager

### ISSUE THREAD

**Issue by neilsonnn** [oculus-samples/Unity-Movement#62]
Can't open samples unless this package is imported locally!

https://docs.unity3d.com/Manual/cus-samples.html

**Comment by sohailshafiiWk** [comment]
Hello, thank you for flagging this. We are investigating ways to distribute the samples that come with our runtime and editor scripts. We will circle back when we have more information.

**Comment by Weibye** [comment]
I would recommend setting up a github action that simply renames ´Samples´ to `~Samples` when pushed to the main branch. This way it would not interfear with any other potential requirements and be isolated to this repo.

**Comment by andkim-meta** [comment]
Hello, we have updated the samples so that this is the case now. Closing task.
