### ISSUE TITLE
Unity Profiler - Body tracking 

### ISSUE THREAD

**Issue by HalfwitSundays** [oculus-samples/Unity-Movement#63]
Hey Devs, 

I'm just looking into how much CPU the body tracking takes up because it seems to be a bit too harsh to be able to add in an environment as well. Can you guys let me know if this lines up on your end or if there's any ways that it can be optimised? I've also turned off Vsync for these tests but just in case it didn't translate to the feature over I changed the FPS goal to 120. Otherwise Vsync would be forcing delay on the more efficient "Just VR camera" comparison.

Just VR camera - No environment - Meta package
FPS Goal = 120fps
Recorded FPS = 119.9FPS
CPU Delay = 7.94ms
GPU Delay = 4.17ms
EarlyUpdate.XRUpdate = 56.3% = 4.46ms delay
FrameEvenets.XRBeginFrame = 2.6% = 0.21ms delay

With Tracking - No environment - Meta package
FPS Goal = 120fps
Recorded FPS = 60.8FPS
CPU Delay = 14.84ms
GPU Delay = 8.80ms
EarlyUpdate.XRUpdate = 53.8% = 7.99ms delay
FrameEvenets.XRBeginFrame = 17.6% = 2.62ms delay

Also, is there any better ways that I could check that a delay is directly related to body tracking? There's the scripts and their associated numbers (e.g. OVRSkeleton.FixedUpdate() at 0.8% - 0.13ms delay) but I feel like that's not registering sensor data etc.

Cheers,
Ezekiel

**Comment by sohailshafiiWk** [comment]
Hello, thank you for the question.

Unfortunately the samples don’t provide a convenient way to measure performance as they are bound pretty tightly to Unity and the design choices made for the scenes.  However, we have recently updated the samples and they should now run at the display frame rate (72 FPS) on the Quest 2.

As far measuring the performance, it seems like you are pretty familiar with the tools. When interpreting the measurements, it is important to distinguish between system cores and the app cores.  Most of the processing for body tracking including the cameras, ML algorithms, and basic IK occur on the system cores and currently consume 3-4 ms, but this doesn’t directly impact the app cores. The interface to these services through OpenXR and Unity bindings adds negligible overhead (sub 0.2 ms).  Finally, there is the retargeting and deformation logic which is variable based on options chosen, but should account for around 1 ms.

Please retest with the latest samples and let us know if this doesn’t answer your questions.

**Comment by sohailshafiiWk** [comment]
Hello, we have not heard from you in a while. We will close this for now. Please reopen if you have any follow-up questions or concerns.
