### ISSUE TITLE
Wrong Hips rotation in HipPinning sample

### ISSUE THREAD

**Issue by dledents** [oculus-samples/Unity-Movement#64]
The Hips rotation is wrong if I turn my head during sample staring. 
Steps to reproduce:
1. Open MovementHipPinning sample scene.
2. Disable "SceneSelectMenu" and "HipPinningMenu".
![image](https://github.com/oculus-samples/Unity-Movement/assets/32562250/a988fdfb-a28a-4540-b4da-81827588a477)
3. Build and run the sample.
4. Turn the head with the VR Helmet left while the app is starting (while there is a unity loading screen).
5. Turn the head with the VR Helmet in a usual position to look forward. 
6. Mirrored model's Hips and Legs are turned. I expect them to be directed towards me.
![com android permissioncontroller-20240325-125553](https://github.com/oculus-samples/Unity-Movement/assets/32562250/08fbe2d3-109e-42a2-926c-b4ecc2f91bf6)

**Comment by sohailshafiiWk** [comment]
Hello, please check commit [21bdcbc](https://github.com/oculus-samples/Unity-Movement/commit/21bdcbcfe981c8a493bc51e7a602037fe25e7404) or newer ("
fix(Runtime): Properly align feet in hip pinning sample") on the dev branch for a fix that should address hip and feet misalignment issues, which should cover the edge case that you described as well. Please note that the scene is meant to be used with the menus enabled for calibration purposes. Let us know if the problem still occurs for you or not.

**Comment by sohailshafiiWk** [comment]
Hello, we have not heard from you in a while. We will close this for now. Please reopen if you have any follow-up questions or concerns.
