### ISSUE TITLE
At time of locomotion head is shaking 

### ISSUE THREAD

**Issue by ramkeshcse084** [oculus-samples/Unity-Movement#67]
Hello there ,
I am using Full body locomotion on ready player me . At time of locomotion my avatar head  is shaking . Is there anything we can do to stop head shaking ?

https://github.com/oculus-samples/Unity-Movement/assets/25951438/8ebff775-318b-408f-815e-191fcc7c2735

**Comment by mvaganov-meta** [comment]
The head motion is pulled from the locomotion animation controller. You can find it by clicking on the Controller connected to your Animator. If you are using the LocomotionController from our sample, double-click on the Grounded state (from the animator view) to find the Blend Tree. Select the Blend Tree and notice that there are animations listed, associated with different joystick positions. The head shaking you see is baked into those animations.
![image](https://github.com/oculus-samples/Unity-Movement/assets/165341825/bbce86a4-fe84-4ca7-b18d-a1b70691e21f)

If you want to change the animation of the head, you need to change those animations, or apply an animation constraint to set the specific desired position/rotation of the head. The animation constraint would have to go after the "PartiallyReapplyAnimatedBodyPose" object in the character's Rig child object.
![image](https://github.com/oculus-samples/Unity-Movement/assets/165341825/36ed5f8a-7c4b-4914-947a-1c88b2fe32e5)

There are several tutorials online that show how to create "unity rig constraints" including several YouTube tutorials.

**Comment by ramkeshcse084** [comment]
Thank you . I have replied  in #68 . 
I will try to add constrain . 
Thank You .

**Comment by ramkeshcse084** [comment]
I fixed this issue by applying contraint . Thank You

**Comment by andkim-meta** [comment]
We are glad you were able to resolve this issue. Closing the issue now.
