### ISSUE TITLE
Slow locomotion Player shaking and jumping and when coming from locomotion leg fall in ground for a moment 

### ISSUE THREAD

**Issue by ramkeshcse084** [oculus-samples/Unity-Movement#68]
Hello ,
I am working on Locomotion . Facing some issue need guidance . When moving with joystic very slowly avatar started shaking and jumping around . I think it should be idle to locomotion transition but it is not smooth . When stop from locomotion avatar leg fall in ground for a moment and transition is not smooth between locomotion and idle . Please help me out .
Here is ref. video 
[](https://drive.google.com/file/d/1qoV8P2MPV2XGWv3WTf-lKJLeFKQ8gKMS/view?usp=sharing)

**Comment by mvaganov-meta** [comment]
Please repost the video.

In the mean time, see if the transition behavior is better after adjusting the values of the Pos X and Pos Y columns of the Blend Tree in the inspector (see [issue #67](https://github.com/oculus-samples/Unity-Movement/issues/67) which is likely related). Look at the rows that have a "Walk" motion, and try increasing the PosX/PosY value to something between 0 and 1.

**Comment by ramkeshcse084** [comment]
Thank you for quick response . It is really helpful .

https://github.com/oculus-samples/Unity-Movement/assets/25951438/81d9dde9-1eee-40be-ba4c-8b497c86b0e4

I will play around X and Y value . I have changed walk and run animation from mixamo but issue was there even leg behavior was changing . My take was take thresold of joystic on certain level and then give value to animator but i was not getting code where these value is getting pass to animator . Hope this video will help you to understand our issue .
 For smooth animation transition i tried to add LocomotionAnimationConstraintblender but it does not show effect . In rig i just copy these[ref image] from locomotion sample scene rig because by default it was not in my rig . Correct me if i am wrong anywhere . One more quesion Can we add any 3rd party plugin for leg movement animation and animation transition like leg animator , Final IK etc ?
Thank You 
![image](https://github.com/oculus-samples/Unity-Movement/assets/25951438/8b8c5585-ce85-4696-af56-a3853343f0a5)
 
![image](https://github.com/oculus-samples/Unity-Movement/assets/25951438/903d04a7-4ab9-47dc-8e8c-81eabfdb5c29)

**Comment by sohailshafiiWk** [comment]
Hello. It looks like "RememberAnimatedBodyPose" and "PartiallyReapplyAnimatedBodyPose" constraints (and any constraints in general) need to be children of the "Rig" transform. A good reference for animation rigging can be found here in case you are curious: https://docs.unity3d.com/Packages/com.unity.animation.rigging@1.3/manual/RiggingWorkflow.html.

Furthermore, "RememberAnimatedBodyPose" probably needs to be before the "RetargetingConstraint" to capture animation data before retargeting is done, and "PartiallyReapplyAnimatedBodyPose" need to be after all constraints (after the constraint that uses deformation). The character in the locomotion scene can serve as a good template to reference.

In regards to other tools, while we do not actively support integrations with third party plugins such as FinalIK, it should be possible for developers to add any such plugin to create compelling apps.

**Comment by ramkeshcse084** [comment]
Hello , Thank You .
After following above player is not going in ground . At time of slow move player is shaking even at time of backward walk it is more visible . It feels it's getting enough value to run .
