### ISSUE TITLE
mouthClose shapekey missing

### ISSUE THREAD

**Issue by loicbramoulle** [oculus-samples/Unity-Movement#69]
Hi, I'm using Aura & high fidelity guy to transfer shapekeys to other avatars/characters, for film ect.. using mocap fusion to do mocap. But both fbx seems to be missing the mouthClose shapekey/blendshape, they have no shape that can keep the lips shut while the jaw is opened (jawDrop). But when testing the .apk demo with Aura, like any Meta avatar she does have the mouth close, I can open the jaw and keep my lips shut, which is critical for any "B", "P" sounds for lip-synch ect..
Is there any exact list of shapes that are actually used in Meta natural expression facial ? so we could check if there's any data missing from our current facial profile / shapekeys/blendshpaes names list.
Interestingly the Quest pro seems to support ARKit too, which has the mouthClose shapekeys (which would be named differently in Meta profile if it exists I guess) so dunno what's happening under the hood for the mouth to only be able to close on AUra in the .apk demo in standalone, not in PC apps.
Thanks for any help.

**Comment by loicbramoulle** [comment]
Ok it was my bad, I missed it, it's named: lipsToward
amazing ! so it's 69 shapes in total including the 7 tongue shapes.

**Comment by sohailshafiiWk** [comment]
Hello, we are happy that you were able to resolve this issue. We will close it for now, but please re-open it if you run into problems with lips toward. For reference all of the blendshapes are documented here: https://developer.oculus.com/documentation/unity/move-face-tracking/. These relate to the `FaceExpression` enum.
