### ISSUE TITLE
Geometry issues on PC version

### ISSUE THREAD

**Issue by kenthinson** [oculus-samples/Unity-Movement#7]
The face has geo issues on the PC demo. It shows a crack in the face on the right side only and only when doing some expressions / angles.  Not really important for development / sdk. But Just thought I would give the Meta team a heads up in case they want to fix it. 

![Untitled](https://user-images.githubusercontent.com/2245494/204340404-fd36441c-4dbd-49aa-af6d-aec09b1bb727.png)

**Comment by sohailshafiiWk** [comment]
Thank you for reporting this, we will looking into this artifact.

**Comment by sohailshafiiWk** [comment]
The samples are provided are used to illustrate the body and face tracking services. As such, they are not tested under different rendering pipelines and configurations. This image renders well under UPM when we experimented. If you have other issues regarding the tracking services themselves, please raise an issue.  We will close this issue for now. Thank you.
