### ISSUE TITLE
Clean Scene / Shuttering when I move left and right every few seconds with Refresh Rate 90hz (72hz everything is ok).

### ISSUE THREAD

**Issue by MonologicGames** [oculus-samples/Unity-Movement#72]
Hello,

In a clean sample scene, unfortunately, on a build for the Quest 3, when I move left and right, both my mirrored character and I experience shuttering visible in the goggles, which makes it uncomfortable.

Interestingly, the problem is only when refresh rate is set to 90hz . I would appreciate any information on what could be causing this problem.

Thanks in advance for help,
Damian.

**Comment by MonologicGames** [comment]
The issue becomes much more noticeable when I turn off hand tracking, which also disables the upper body tracking, leaving only 3-point tracking operational.

**Comment by sohailshafiiWk** [comment]
Hello, we have been investigating this issue. Can you provide a video recording of what you see so that we can make a proper comparison?
