### ISSUE TITLE
arms are moving backward when I change the position of avatar

### ISSUE THREAD

**Issue by Tikitaka02** [oculus-samples/Unity-Movement#73]
Hello,

I have an issue with retargetting avatar after changing the position of the avatar. It seems that the avatar is correctly retargetted when the avatar is at [0,0,0] position, but when I move the avatar forward. All the arm movements in front of me is retargetted behind me on avatar. I am using unity 2022.3.14f1 and movement sdk 5.0.1.

I appreciate your support.

**Comment by sohailshafiiWk** [comment]
Hello, is this occurring for the robot in our retargeted scene or for your own, custom character? If for the latter, please see if "Translation DoF" has been turned on (see https://developer.oculus.com/documentation/unity/move-body-tracking/#setting-up-a-character-for-body-tracking for details).

**Comment by sohailshafiiWk** [comment]
Hello, we have not heard from you in a while. We will close this for now. Please reopen if you have any follow-up questions or concerns.
