### ISSUE TITLE
In locomotion animation direction is opposite if we turn face on start of app - Bug in Locomotion sample too

### ISSUE THREAD

**Issue by ramkeshcse084** [oculus-samples/Unity-Movement#75]
Hello Team,

I encountered a surprising bug that I'd like to report. When I open the app and initiate locomotion, such as walking forward, the forward animation plays correctly. However, if I open the app, turn in the opposite direction to last time, and then start walking forward, the backward animation plays instead. This issue is quite unexpected.

I've attached a video for reference to help clarify the problem. Initially, I thought there might be a mistake in our implementation, but I have verified that the same issue occurs even in the locomotion sample scene.

We are considering using the Meta Movement SDK for our project, but we've found the response times to be slow, and sometimes there is no response at all. Could you please assist us? We are currently stuck and would appreciate any help you can provide.
 In the video first half is the reverse one and second half shows correct animation.

Thank you!

 
https://github.com/oculus-samples/Unity-Movement/assets/25951438/d168f9fb-0077-430a-abb4-115dbcd3e96c

**Comment by sohailshafiiWk** [comment]
Hello, we have applied a fix that should address this problem to our dev branch as of the commit https://github.com/oculus-samples/Unity-Movement/commit/5fa894c629a38b8982b2da641cba86bc45f32a58. Please note that it should address the problem on the embodied character in the relevant sample scene, and that the `MovementSDKLocomotion` component's `OnUserInputChangeJoystickDir`, not `OnUserInputChange`, now needs to be hooked up to the `InputHorizontalVertical` field on `AnimatorHooks`. Please reference the `MovementLocomotion` scene to see how that is implemented.

**Comment by sohailshafiiWk** [comment]
In regards to the bug where the animation does not match the motion of movement, we addressed this in #dev as mentioned in https://github.com/oculus-samples/Unity-Movement/issues/75, however the fix applies to the embodied character in the sample. Can you confirm that it works for you or not?
