### ISSUE TITLE
I can't use body tracking in Unity

### ISSUE THREAD

**Issue by tayamaYuto** [oculus-samples/Unity-Movement#76]
I was performing Body Tracking using Unity-Movement, but the following warning occurred, and I was no longer able to move the avatar.

Warning:
[OVRPlugin] [XRCMD][failure] [XR_ERROR_INITIALIZATION_FAILED]: xrLocateBodyJointsFB(m_xrBodyTracker, &info, &locations), arvr\projects\integrations\OVRPlugin\Src\Util\CompositorOpenXR.cpp:9488

Does anyone know how to solve this?

Unity version: 2022.3.11f1
MetaQuest2

Using InteractionRigOVR and BuildingBlocks' CameraRig did not change anything.
I was using ArmatureSkinningUpdateTpose for the avatar.

**Comment by sohailshafiiWk** [comment]
Hello. To be clear, body tracking was working at some point and then it started to fail? Can you check the project setup tool (Oculus->Tools->Project Setup Tool) and let us know if any errors issues or recommended items appear? Furthermore, has our "MovementRetargeting" (https://github.com/oculus-samples/Unity-Movement/blob/main/Samples~/BodyTrackingSamples/Scenes/MovementRetargeting.unity) sample scene worked for you?

**Comment by tayamaYuto** [comment]
> body tracking was working at some point and then it started to fail?
That's correct. Initially, it was working fine, but after leaving it for about a day, the above error started to occur.

Regarding MovementRetargeting, it was also working fine at first, but now it shows the same warning as in my scene, and I can't move the avatar.

In the Project Setup Tool, I confirmed this error, but even after selecting "fix all," the error still remains.

![スクリーンショット 2024-05-21 130743](https://github.com/oculus-samples/Unity-Movement/assets/132319235/b5b588d5-27de-4174-8b3c-9723372cc7b4)

**Comment by sohailshafiiWk** [comment]
Hello, can you tell me:

1. What your OS is (Windows 10 or 11)?
2. The OS version of your Quest device, and the version of your Meta Quest Link software (found in the Settings -> Developer screen)?
3. The Meta XR SDK versions that you are using in Unity, and a screenshot of your OVRCameraRig (Quest Features->General and also Movement Tracking sections)?"

**Comment by tayamaYuto** [comment]
Ok,
I got a MetaQuest3 and set it up the same way, but the same error occurred.
I'll provide the information about MetaQuest3.


OS is Windows11
The OS version of my Quest device is SQ3.220605.009.A1
Version of Quest Link software is 65.0.0.499.343 (65.0.0.499.343)
Meta XR All-in-One SDK 65.0.0

![スクリーンショット 2024-05-22 144302](https://github.com/oculus-samples/Unity-Movement/assets/132319235/a8b24f85-066e-458b-8c5e-dce02580d9eb)

**Comment by sohailshafiiWk** [comment]
Hello, is it possible to gather logs and provide them here by following the steps outlined in https://developer.oculus.com/documentation/unity/unity-link/#link-log-gathering-from-unity-editor-and-oculusloggather-tool? Furthermore, would you be willing to share the output of adb logcat to us? Can you provide a screenshot of the Settings->Beta section of your Meta Quest PC app?

**Comment by tayamaYuto** [comment]
How should I send the logs? Is it okay to do so on this issue? I am concerned about personal information being leaked.

**Comment by tayamaYuto** [comment]
For now, I will attach the log data that seems safe to share.
[Uploading Editor.log…]()

**Comment by sohailshafiiWk** [comment]
Hello, we don't see a log uploaded. Can you please try again?

**Comment by tayamaYuto** [comment]
oh, sorry

[Editor.log](https://github.com/user-attachments/files/15542459/Editor.log)

[Oculus_Logs_DESKTOP-LVFU8HQ_20240602_170348.zip](https://github.com/user-attachments/files/15542476/Oculus_Logs_DESKTOP-LVFU8HQ_20240602_170348.zip)

**Comment by sohailshafiiWk** [comment]
Thank you for uploading the log files. We are currently looking into this problem.

**Comment by tayamaYuto** [comment]
Thank you so much!!!

**Comment by tayamaYuto** [comment]
@sohailshafiiWk 
How is this issue progressing?
After taking a short break and running it again, both the sample armatureTpose avatar and the Robot Kyle avatar we were using worked properly.

I'm still concerned as I'm not sure when the same issue might occur again, but for now, it seems to have been resolved.

I'm working on resolving the issue with Robot Kyle where there seems to be a misalignment, possibly due to missing bones. Do you have any ideas or suggestions?

I believe the problem lies in the fact that Robot Kyle lacks rigs for the Upper Chest and Chest.

**Comment by tayamaYuto** [comment]
It seems that repeatedly playing the scene in Unity results in encountering errors. Restarting appears to allow body tracking to function again.

**Comment by sohailshafiiWk** [comment]
Hello, we have investigated this issue internally. Is this issue occurring while trying to initiate Link after device has slept for a while? Are you starting Link before donning the HMD?

**Comment by tayamaYuto** [comment]
At the time of reporting this issue, I was using AirLink, and I recall reconnecting AirLink before pressing the run button in Unity since the connection would drop when the HMD was removed.

Currently, I am using a USB connection because the frequent disconnections were bothersome.

**Comment by tayamaYuto** [comment]
Since the device sometimes goes into sleep mode, I believe the steps I followed were:

1. Wake from sleep
2. Start AirLink
3. Run Unity

**Comment by tayamaYuto** [comment]
I encountered the same issue again when I connected MetaQuest from sleep mode using AirLink.

**Comment by sohailshafiiWk** [comment]
Can you try adding an extra step in your startup before running unity?  Please don the headset and visually confirm that you see the Link control scene (not sure what you call this) to verify that the connection is established.

**Comment by tayamaYuto** [comment]
Once I switched from AirLink to a USB connection, it started up without any issues. Thank you for your support.

**Comment by sohailshafiiWk** [comment]
Thank you for letting us know. We will close this issue.
