### ISSUE TITLE
Head movement results in arm and hand movement

### ISSUE THREAD

**Issue by AndiHal** [oculus-samples/Unity-Movement#77]
Hi,

I am working on an application where the player is sitting in front of a physical table. The player should lay his/her hands on the table. In VR there would be a replica of that table so the player could also see their virtual hand laying on a virtual table. In the scene, the player has a mirror in front of them so they can see their whole body.
The problem is that when I look at my virtual hand it (approximately) lays on the table. When I look away from the hand, it moves downwards through the table. 
When I have the grey interaction hands activated, one can see that they are still on the table. So the headset does not loose track of the hands when I look away from them. I tried quite a few settings but it seems that this behavior always shows. 
I am using version 5.10 of the movment sdk.

https://github.com/oculus-samples/Unity-Movement/assets/83827769/301195c1-2023-4936-822c-22ba3b128345

**Comment by sohailshafiiWk** [comment]
Hello. To confirm by "interaction hands" do you mean the ISDK hands? Does the body tracking hand exhibit this behavior with the Body Tracking Fidelity set to High, Low or both?
