### ISSUE TITLE
com.oculus.bodyapiservice stops working

### ISSUE THREAD

**Issue by pwc-metaverse** [oculus-samples/Unity-Movement#8]
Having closely followed the instructions for setting up the samples, whenever we try to run the scenes over oculus link the error `com.oculus.bodyapiservice keeps stopping` appears. This has been tested on a quest 2 and a pro headset, with both cable and airlink. In the oculus app the developer mode beta settings for face and eye tracking are enabled. The scene then proceeds to run but without face or eye tracking. No obvious warnings or errors appear in the Console log.

**Comment by sohailshafiiWk** [comment]
I'm sorry that you are encountering this. A few questions:

1. Have you tried the Public Test version of the Oculus PC app? See https://www.meta.com/help/quest/articles/headsets-and-accessories/oculus-rift-s/public-test-channel/
2. Does your project have XR Plug-in installed? Navigate Player settings under XR Plug-in Management, and see if "Oculus" is checked.
3. Do these problems happen only over Link or via builds as well?

**Comment by sohailshafiiWk** [comment]
Closing for now. Please re-open if this occurs again.

**Comment by mawstr001** [comment]
i also have the same issue but no resolution seems to be found on the internet.  i saw one user mentioned that it was an issue with the oculus developers account, somehow resetting it works.  Any clues on how to "restart" the developer mode?
