### ISSUE TITLE
Better quality scaling for a short player character

### ISSUE THREAD

**Issue by MonologicGames** [oculus-samples/Unity-Movement#80]
Hello,

Do you have any idea how to make shorter characters look better? Because currently they remain in the original scale, the shoulders are acting up - generally it doesn't look good.

Normal hight player:
![image](https://github.com/oculus-samples/Unity-Movement/assets/58339467/56259e8c-70a3-47fc-9ed7-ea4330d7bbf2)

Small Player:
![image](https://github.com/oculus-samples/Unity-Movement/assets/58339467/ce2af3c2-663d-41ac-8ef0-fccb9990f510)

Thanks in advance!

**Comment by andkim-meta** [comment]
Hello, for resolving the differences in proportions between the tracked user and the model, we recommend using the retargeting stack described in the documentation: https://developer.oculus.com/documentation/unity/move-body-tracking/
