### ISSUE TITLE
I cant setup this SDK for multiplayer. I need special help.

### ISSUE THREAD

**Issue by Robostep21** [oculus-samples/Unity-Movement#81]
Im using Photon Fusion2 and this SDK on Oculus Quest 3.
![изображение_2024-07-12_172839924](https://github.com/user-attachments/assets/491cfc7c-1b26-42ab-b636-3bae8deb174c)

**Comment by andkim-meta** [comment]
Hello, we can provide some advice for setting up Movement SDK for multiplayer. We suggest networking the final pose after retargeting and constraints, and optimizing the serialized pose before sending it. Additionally, consider implementing interpolation when applying the received pose to the receiving client. You can remove all other components except for the one responsible for deserializing the data on the player's side and simply update the character with the received pose. The pose data should be compressed and sent at a reasonable update rate, using networking optimization techniques. An article that explains some techniques can be found here: https://gafferongames.com/post/snapshot_compression/. For information about how to use Photon Fusion 2, please refer to their tutorials: https://doc.photonengine.com/fusion/current/tutorials/host-mode-basics/overview. To summarize, the host performs all logic to make the character move, while the client has only the skinned mesh that is driven by the result of the host's work.
