### ISSUE TITLE
Creating AR app by using Unity-Movement SDK

### ISSUE THREAD

**Issue by MehranRastegarSani** [oculus-samples/Unity-Movement#85]
Hi, Thanks for the great work.

I want to know if I can use this SDK in an AR app with the Passthrough feature.

**Comment by MehranRastegarSani** [comment]
Thanks. In my case, I need to track only the upper body. However, in the OVRCameraRig, I cannot enable the Passthrough mode. Please see the screenshot.
I use:
unity - 2022.3.19f1
Meta XR Core SDK - 68.0.2

As is shown in the screenshots, it says, "require passthrough capability to be enabled in the general section", but there is no passthrough option in the general section.

![1](https://github.com/user-attachments/assets/63df0ee0-9a40-4b13-93b4-44a98672a8f5)
![2](https://github.com/user-attachments/assets/a9e4e66f-1634-4339-b01e-bcc492ee319a)
![3](https://github.com/user-attachments/assets/87fea8c6-9a2e-455a-b91a-288a5c46f67a)

**Comment by MehranRastegarSani** [comment]
Thanks. I could run it on passthrough, and it works great.

Now, I want to know if I can put the avatar in front of myself (like a mirror) instead of having it on my body.

**Comment by andkim-meta** [comment]
Hello, the body tracking samples (https://developer.oculus.com/documentation/unity/move-samples/) can be used as a reference for displaying a mirrored character. If the original issue with passthrough has been resolved, please close this issue and create a new issue if you are still encountering issues.

**Comment by MehranRastegarSani** [comment]
Thanks again for your help.
I will check it and open a new issue if I have any questions.
