### ISSUE TITLE
when I configure this project，I can not find the shadervariant collection

### ISSUE THREAD

**Issue by ZhenyanSun** [oculus-samples/Unity-Movement#9]
Dear team, I have copy the shadervariant from github and paste into my project under assets folder, but I still can not find it in my unity, could you give me any advice?
![image](https://user-images.githubusercontent.com/73994342/212838816-fa281e5c-cd6c-4b15-be6f-0e12c89ffd08.png)

![image](https://user-images.githubusercontent.com/73994342/212838964-ec786b17-843d-4590-ae78-63eee7209ea6.png)

**Comment by sohailshafiiWk** [comment]
I'm sorry that you are encountering this. Can you please check the file extension of the shader variants file? In Windows Explorer, please use the "Type" column and make sure it's SHADERVARIANTS (ending in .shadervariants). It might be that the files you've added are being treated as a "Text Document" (.txt).

**Comment by ZhenyanSun** [comment]
> I'm sorry that you are encountering this. Can you please check the file extension of the shader variants file? In Windows Explorer, please use the "Type" column and make sure it's SHADERVARIANTS (ending in .shadervariants). It might be that the files you've added are being treated as a "Text Document" (.txt).

problem is solved thanks.

**Comment by sohailshafiiWk** [comment]
That's great! Have fun trying out the samples.
