### ISSUE TITLE
Question: Is that possible to disable tracking position?

### ISSUE THREAD

**Issue by MehranRastegarSani** [oculus-samples/Unity-Movement#91]
Hi, Thanks for your great contribution. 

I want to know if it is possible to use this SDK to update only the avatar rotation based on the user.
I want to update the avatar position based on another object, not based on the user's position. To do this, I need to disable tracking and updating positions while using this SDK.
Could you please guide me on how I can do this?

**Comment by MehranRastegarSani** [comment]
Thank you so much for the instructions. I will try them and let you know.
In part of my project, I also need to compare the arm position ( wrist, elbow and shoulder) with a pre-captured animated avatar. So, I think It would be very beneficial if I could directly access the tracking value.
Could you please explain how I can access the tracking value?

**Comment by sohailshafiiWk** [comment]
Each class that inherits from `OVRSkeleton.cs` whether that is `OVRCustomSkeleton.cs` or `RetargetingLayer.cs`, has a public `Bones` array that can be indexed by `BoneId`. You can access it via `FullBody_LeftHandWrist` for instance to access that `OVRBone`'s `Tranform` field to easily access world space values. 

You can also access `OVRBody`'s `GetSkeletonPoseData` (which `OVRSkeleton` uses) in case you want values closer to what the tracker provides, however you have to do some conversion as you can see in `OVRSkeleton`'s `UpdateSkeleton` function. For instance, it relies on `FromFlippedZVector3f` and `FromFlippedZQuatf`, and those values are local to the skeleton that they belong to.
