### ISSUE TITLE
 NetworkPoseRetargeterBehaviourNGO without Spawner

### ISSUE THREAD

**Issue by hansvana** [oculus-samples/Unity-Movement#94]
Using Unity 6000.0.25f1 with Meta XR All-in-One SDK 71.0.0 and Meta Movement 71.0.1.

I am working on getting the Movement SDK working with NGO's. I am _not_ using the Network Pose Retargeter Spawner NGO, nor am I using any building blocks. I assume this is part of why I am having problems. However I _did_ get it work, but I would like more information on whether this is a bug or a feature.

The prefab on the client has all the normal components 
<img width="302" alt="11" src="https://github.com/user-attachments/assets/2a431a10-cb54-4984-8b44-7255ca03c2ef" />

The prefab variant on the server has these
<img width="342" alt="12" src="https://github.com/user-attachments/assets/9292bcc5-9e6b-4031-b08f-20d0eb38457e" />

I realized the NetworkPoseRetargeter was not sending or receiving any data, because the `_initialized` property was never set to true. This is supposed to be done by `Setup()`, which is called from `NetworkPoseRetargeterBehaviourNGO.OnCharacterIdChanged()`, but only if `_characterId` is not 0. I see `_characterId` is a network variable, but I have no idea where to set this. Maybe this is avatars related (which I am not using)?

Would you advise making my own copy of `NetworkPoseRetargeterBehaviourNGO` which bypasses the `_characterId` check, or am I missing something?

**Comment by andkim-meta** [comment]
Hello,

If you wish to use the `NetworkPoseRetargeterBehaviourNGO` without the `NetworkPoseRetargeterSpawnerNGO`, we would recommend calling `INetworkPoseRetargeter.Setup(false)` function manually on your instantiated character, as it's a public function. `CharacterId` is set by the `NetworkPoseRetargeterSpawnerNGO` and is used only for instantiating different character prefabs, so if you are not using the `NetworkPoseRetargeterSpawnerNGO`, it's not required to update that network variable.

**Comment by hansvana** [comment]
This is what I've resorted to doing, thank you for your response. I hope the documentation will one day come to reflect all the hard work you've been doing.
